# Generated by Django 4.2.3 on 2023-10-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
