# Generated by Django 4.2.7 on 2023-12-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 14, 54, 4, 672966, tzinfo=datetime.timezone.utc)),
        ),
    ]
