# Generated by Django 4.2.7 on 2023-12-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 15, 42, 19, 517666, tzinfo=datetime.timezone.utc)),
        ),
    ]
