# Generated by Django 4.2.7 on 2023-12-19 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_history_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 16, 25, 4, 894631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='p_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('image', 'Image')], default='image', max_length=6, verbose_name='валюта'),
        ),
    ]
