# Generated by Django 4.2.7 on 2023-12-23 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_history_expiration_date_alter_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 21, 0, 8, 560353, tzinfo=datetime.timezone.utc)),
        ),
    ]
