# Generated by Django 4.2.7 on 2023-12-23 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_history_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 21, 13, 12, 136379, tzinfo=datetime.timezone.utc)),
        ),
    ]
