# Generated by Django 4.2.7 on 2023-12-23 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_history_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='настоящее имя пользователя'),
        ),
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 21, 19, 2, 927288, tzinfo=datetime.timezone.utc)),
        ),
    ]
