# Generated by Django 4.2.7 on 2023-12-23 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_history_expiration_date_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 21, 34, 18, 703214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
