# Generated by Django 4.2.7 on 2023-12-24 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_history_expiration_date_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 12, 43, 0, 882127, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('follower', 'following')},
        ),
    ]
